<?php 

function list_ipsums(){
	
	$array=array(
		"Technobabble", 
		"Doctor Who",
		"Video Games",
		"Star Trek",
		// "RPGs",
		// "Star Wars",
		"Fallout",
		// "Batman"
		"Pokemon",
	);
	return $array;
}

function list_videogames() {
	$array=array(
		"1-UP",
		"3DS",
		"8-bit",
		"A Boy and his Blob",
		"AAA",
		"achievement unlocked",
		"adventure game",
		"analog stick",
		"arcade game",
		"artifical intelligence",
		"Atari",
		"attract mode",
		"auto-fire",
		"auto-save",
		"avatar",
		"beat 'em up",
		"beta",
		"boss",
		"bug",
		"bullet hell",
		"Burger Time",
		"cartridge",
		"CD-ROM",
		"cel-shaded",
		"cheat code",
		"chiptune",
		"closed beta",
		"co-op",
		"coin-op",
		"collectibles",
		"combo",
		"console",
		"controller",
		"cowabunga",
		"crafting",
		"crash",
		"credits",
		"cut-scene",
		"D-pad",
		"death match",
		"demo",
		"developer",
		"difficulty setting",
		"directional pad",
		"Donkey Kong",
		"double jump",
		"Dr. Wily",
		"Dragon Quest",
		"DS",
		"easter egg",
		"edutainment",
		"experience points",
		"EGM",
		"Famicon",
		"fatality",
		"finish him",
		"fire flower",
		"first-party",
		"first-person shooter",		
		"frag",
		"frame-rate",
		"freakin' camper",
		"friend code",
		"Galaga",
		"Game Genie",
		"GameBoy",
		"GameCube",
		"GamePro",
		"Genesis",
		"god mode",
		"goddamn casuals",
		"Goomba",
		"Grand Theft Auto",
		"griefer",
		"grinding",
		"Guybrush Threepwood",
		"hack and slash",
		"hack",
		"hadoken",
		"hardcore",
		"heads-up display",
		"headshot",
		"healer",
		"high score",
		"hit points",
		"homebew",
		"HUD",
		"indie",
		"Inky",
		"invincibile",
		"isometric",
		"Koopa Troopa",
		"lag",
		"last boss",
		"Leeroy Jenkins",
		"level up",
		"level",
		"Light Phaser",
		"lightgun",
		"Link",
		"load game",
		"loot",
		"magic points",
		"Mame",
		"Maniac Mansion",
		"Mario",
		"Masamune",
		"Mega Drive",
		"Metroid",
		"midcore",
		"minesweeper",
		"mini-boss",
		"mode 7",
		"motion-capture",
		"multiplayer",
		"Murasame",
		"mushrooms",
		"n00b",
		"NES",
		"new game plus",
		"new game",
		"Nintendo",
		"NPC",
		"open world",
		"options",
		"pack-in game",
		"pacu pacu",
		"pixel",
		"platformer",
		"polygon",
		"port",
		"Power Glove",
		"power-up",
		"Princess Toadstool",
		"programmer",
		"pwned",
		"questing",
		"quicktime event",
		"R.O.B.",
		"rag-doll physics",
		"real-time strategy",
		"respawn",
		"retro",
		"role-playing game",
		"ROM",
		"rumble pack",
		"Samus",
		"save point",
		"score",
		"Sega",
		"shareware",
		"Sheng Long",
		"Shigeru Miyamoto",
		"shooter",
		"shoryuken",
		"side-scrolling",
		"sim",
		"simulation",
		"single-player",
		"Solid Snake",
		"spawn point",
		"spawn point",
		"special attack",
		"sprite",
		"sprites",
		"strafing",
		"strategy guide",
		"Super Nintendo",
		"survival horror",
		"tank",
		"tanuki suit",
		"third-party",
		"Tri-force",
		"turbo",
		"turbo",
		"Virtual Boy",
		"warp pipes",
		"Wii",
		"Wiimote",
		"Zelda",

	);
	return $array;
}

function list_fallout() {
	$array=array(
		"Ain't That a Kick in the Head",
		"assault carbine",
		"atomic fire",
		"Benny",
		"Boomers",
		"brahman milk",
		"brahman",
		"Brotherhood of Steel",
		"buffout",
		"caps",
		"caravan",
		"cazadores",
		"chainsaw",
		"chems",
		"combat armor",
		"cowboy hat",
		"cowboy repeater",
		"deathclaws",
		"Doesn't Play Well with Others",
		"downfall of society",
		"Elder",
		"feral ghoul",
		"Galaxy News Radio",
		"ghost",
		"ghouls",
		"Goodsprings",
		"Great Khans",
		"Great War",
		"Hail Caesar",
		"Harold",
		"Hoover Dam",
		"hunting rifle",
		"Hydra",
		"Jet",
		"karma",
		"Lady Killer",
		"laser rifle",
		"lead pipe",
		"Little Lamplight",
		"Lone Wanderer",
		"Love the Bomb",
		"Maria",
		"Megaton",
		"mentat",
		"mercenary",
		"microfusion cells",
		"Mr. House",
		"mutants",
		"NCR",
		"New Vegas",
		"Nuka-Cola",
		"outsider",
		"parcel",
		"Pipboy-3000",
		"platinum chip",
		"Powder Gangers",
		"power armor",
		"prospector",
		"radroach",
		"raider",
		"riot shotgun",
		"RobCo Industries",
		"robot",
		"scavenger",
		"Scourge of Humanity",
		"securitrons",
		"Shishkebab",
		"sledgehammer",
		"Sleeptron 3000",
		"stealth boy",
		"stimpaks",
		"super mutants",
		"super sledge",
		"Survivalist's rifle",
		"terminal",
		"tesla armor",
		"The Burned Man",
		"The Courier",
		"Three Dog",
		"Tunnel Snakes",
		"vaccuum tube",
		"VATS",
		"Vault 101",
		"vault dweller",
		"virtual reality",
		"wanderer",
		"wasteland",
		"wastelander",
		"White Glove Society",
		"yao guai",
		"yes man",
		"Yes, I Play With Dolls",
		"necrotic post-human",
		"glowing one",
		"ghoulification",
		"mole rats",
		"bloatfly",
		"centaur",
		"dog",
		"fireant",
		"mirelurk",
		"radscorpion",
		"dwarf",
		"gecko",
		"iguana",
		"mutated rat pig",
		"bighorner",
		"nightkin",
	);
	return $array;
}

function list_batman() {
	$array=array(
		"Joker",
		"Where does he get those wonderful toys",
		"Bruce Wayne",
		"Gotham City",
		"Arkham Asylum",
	);
	return $array;
}

function list_technobabble() {
	$array=array(
	);	
	$array=array_merge($array,list_startrek_technobabble(), list_starwars_technobabble(), list_doctorwho_technobabble() );
	return $array;
}

function list_starwars_technobabble() {
	$array=array(
		"power converter",
		"carbon scoring",
		"coolant",
		"deflector grille",
		"subsonic field emitter",
		"thermal exhaust port",
		"navcomputer",
		"Midochlorians",
		"phototropic shielding",
	);
	return $array;
}

function list_starwars() {
	$array=array(
		"tautans",
		"Mos Eisley",
		"lightsaber",
		"stormtrooper",
		"wookie",
		"Yoda",
		"Battle of Yavin",
		"Boba Fett",
		"jedi",
		"hyperspace",
		"Imperial Star Destroyer",
		"light side",
		"dark side",
		"New Republic",
		"Sith",
		"the Force",
		"Hutt",
		"X-Wing",
		"TIE Figher",
		"Clone Wars",
		"mind trick",
		"bantha",
		"battle droid",
		"C-3PO",
		"droid",
		"ewoks",
		"Gungan",
		"Millenium Falcon",
		"rancor",
		"tusken raider",
		"Rogue squadron",
	);
	$array=array_merge($array, list_starwars_technobabble() );
	return $array;
}

function list_pokemon() {
	$array=get_csv_path();
	return $array;
}

function list_doctorwho() {
	$array=array(
		"TARDIS",
		"Amy Pond",
		"sexy",
		"Pandorica",
		"Dalek",
		"Cyberman",
		"The Silence",
		"Weeping Angels",
		"survivor's guilt",
		"Time-Lord",
		"Gallifrey",
		"Last Great Time War",
		"companions",
		"regenerate",
		"run",
		"Sycorax",
		"Lupine Wavelength Haemovariform",
		"London",
		"Scotland",
		"Torchwood",
		"Canary Wharf",
		"New New York",
		"New Earth",
		"You are not alone",
		"the Doctor",
		"the oncoming storm",
		"John Smith",
		"the bringer of darkness",
		"defender of the Laws of Time",
		"hello sweetie",
		"pretty-boy",
		"spaceman",
		"martian boy",
		"a mad man with a box",
		"raggedy doctor",
		"space Gandalf",
		"the king of ok",
		"time boy",
		"chin-boy",
		"I don't want to go",
		"don't blink",
		"Sally Sparrow",
		"Sonic",
	);
	$array=array_merge($array, list_doctorwho_technobabble() );
	return $array;
}

function list_doctorwho_technobabble() {
	$array=array(
		"sonic screwdriver",
		"time windows",
		"time vortex",
		"matter condensation",
		"thought-cube",
		"single molecule transcription",
		"skeletoid",
		"soul extractor",
		"quarantine beacon",
		"chameleon arch",
		"chronoforge",
		"transmat",
		"truth field",
		"stasis cube",
		"relativity map",
		"reverse tachyon-chronon",
		"telepathic-barrier",
		"psychic paper",
		"cloaking field",
		"computer sphere",
		"crucible energy core",
		"dimension vault",
		"polycarbide",
		"progenitor",
		"videoscope",
		"visualiser",
		"voltoscope",
		"temporal shift",
		"temporal stabiliser",
		"time controller",
		"time corridor",
		"schizoid accelerator",
		"seismic detector",
		"gravity beam",
		"gravity bubble",
		"gunstick",
		"bio-electric dampening field",
		"dalekanium",
		"psycho-kinetic threshold manipulator",
	);
	return $array;
}

function list_startrek() {
	$array=array(
		"admiral",
		"Andoreans",
		"Argus X",
		"assimiliate",
		"astrometrics",
		"atmosphere",
		"away team",
		"Bajoran",
		"beam me up",
		"Betazoid",
		"boarding party",
		"boldly go",
		"borg cube",
		"borg drones",
		"borg",
		"bridge",
		"cargo hold",
		"Data",
		"deep-space",
		"Delta quadrant",
		"diplomatic",
		"Earth",
		"emergency medical hologram",
		"engineering",
		"Enterprise",
		"fencing",
		"galaxy",
		"Gene Roddenberry",
		"Genesis device",
		"holodeck",
		"hydrophonics",
		"James T. Kirk",
		"Khan",
		"Klingon",
		"Kobayashi Maru",
		"LCARS",
		"main engineering",
		"Milky Way",
		"mind-meld",
		"Mr. Spock",
		"NCC-1701-E",
		"nebula",
		"Cardassians",
		"Ferengi",
		"dabo girl",
		"first officer",
		"number one",
		"Neutral Zone",
		"peace",
		"phaser banks",
		"photon torpedo",
		"piller-filler",
		"Prime Directive",
		"Q",
		"rear admiral",
		"refit",
		"Romulan",
		"San Francisco",
		"saucer section",
		"scanning",
		"science officer",
		"Scotty",
		"shields",
		"shuttlebay",
		"sickbay",
		"spacedock",
		"Species 8472",
		"sporocystian lifeform",
		"Stardate",
		"Starfleet",
		"starship",
		"stellar cartography",
		"subspace",
		"Sulu",
		"Temporal Prime Directive",
		"temporal vortex",
		"timeship",
		"transporters",
		"Tribbles",
		"turbolift",
		"Vulcan neck pinch",
		"warp core",
		"warp drive",
		"Wolf 359",
		"wormhole",
		"Tiberius",
	);
	
	$array=array_merge($array,list_startrek_technobabble());
	return $array;
}

function list_startrek_technobabble() {
	$array=array(
		"airlock",
		"android",
		"antiproton",
		"antiproton weapon",
		"black star",
		"cloaking device",
		"cochranes",
		"corbomite",
		"data sphere",
		"deflector dish",
		"depolarised",
		"deuterium",
		"dilithium crystal",
		"energy field",
		"graviton burst",
		"gravity well",
		"impulse engines",
		"interplexing beacon",
		"inverse phasing",
		"inverse tachyon beam",
		"level 3 diagnostic",
		"magnetic deflection",
		"matter-antimatter implosion",
		"medical scanner",
		"medical tricorder",
		"sensor beam",
		"antimatter injector",
		"mobile emitter",
		"modulation",
		"nebula",
		"nanoprobes",
		"neutrino emissions",
		"non-corporeal",
		"phaser banks",
		"photon torpedo",
		"piller-filler",
		"plasma coolant",
		"plasma drift",
		"plasma torpedo",
		"positronic network",
		"power drain",
		"probes",
		"proton bursts",
		"quantum phase",
		"quantum slipstream drive",
		"quantum torpedos",
		"replicator",
		"ryetalyn",
		"shields",
		"spatial scission",
		"sporocystian lifeform",
		"stellar cartography",
		"subspace",
		"tachyon beam",
		"tachyon particles",
		"temporal paradox",
		"temporal vortex",
		"timeship",
		"transporters",
		"transwarp coil",
		"transwarp conduits",
		"Theta radiation",
		"turbolift",
		"warp core",
		"warp core breech",
		"warp drive",
		"warp engine",
		"warp nacelle",
		"wormhole",
	);
	return $array;
}