<?php 

function list_ipsums(){
	
	$array=array(
		"Technobabble",
		"Video Games",
		// "RPGs",
		// "Star Wars",
		"Fallout",
		"Star Trek",
		// "Batman"
		"Doctor Who",
		"Pokemon",
	);
	return $array;
}

function list_videogames() {
	$array=array(
		"1-UP",
		"8-bit",
		"A Boy and his Blob",
		"achievement unlocked",
		"adventure game",
		"arcade game",
		"auto-fire",
		"boss",
		"Burger Time",
		"cheat code",
		"co-op",
		"console",
		"controller",
		"cowabunga",
		"crafting",
		"death match",
		"directional pad",
		"Donkey Kong",
		"Dr. Wily",
		"edutainment",
		"EGM",
		"finish him",
		"fire flower",
		"first-person shooter",		
		"freakin' camper",
		"Galaga",
		"GameBoy",
		"GamePro",
		"god mode",
		"goddamn casuals",
		"Goomba",
		"Grand Theft Auto",
		"griefer",
		"grinding",
		"Guybrush Threepwood",
		"hack and slash",
		"hadoken",
		"healer",
		"high score",
		"hit points",
		"indie",
		"Inky",
		"Koopa Troopa",
		"last boss",
		"lightgun",
		"Mame",
		"Maniac Mansion",
		"Mario",
		"Masamune",
		"mini-boss",
		"multiplayer",
		"Murasame",
		"mushrooms",
		"n00b",
		"Nintendo",
		"NPC",
		"open world",
		"pacu pacu",
		"power-up",
		"Princess Toadstool",
		"questing",
		"rag-doll physics",
		"real-time strategy",
		"role-playing game",
		"Samus",
		"save point",
		"score",
		"Sega",
		"Sheng Long",
		"Shigeru Miyamoto",
		"shoryuken",
		"side-scrolling",
		"single-player",
		"Solid Snake",
		"spawn point",
		"special attack",
		"sprites",
		"strafing",
		"strategy guide",
		"survival horror",
		"tanuki suit",
		"Tri-force",
		"warp pipes",
		"Wiimote",
	);
	return $array;
}

function list_fallout() {
	$array=array(
		"Ain't That a Kick in the Head",
		"assault carbine",
		"atomic fire",
		"Benny",
		"Boomers",
		"brahman milk",
		"brahman",
		"Brotherhood of Steel",
		"buffout",
		"caps",
		"caravan",
		"cazadores",
		"chainsaw",
		"chems",
		"combat armor",
		"cowboy hat",
		"cowboy repeater",
		"deathclaws",
		"Doesn't Play Well with Others",
		"downfall of society",
		"Elder",
		"feral ghoul",
		"Galaxy News Radio",
		"ghost",
		"ghouls",
		"Goodsprings",
		"Great Khans",
		"Great War",
		"Hail Caesar",
		"Harold",
		"Hoover Dam",
		"hunting rifle",
		"Hydra",
		"Jet",
		"karma",
		"Lady Killer",
		"laser rifle",
		"lead pipe",
		"Little Lamplight",
		"Lone Wanderer",
		"Love the Bomb",
		"Maria",
		"Megaton",
		"mentat",
		"mercenary",
		"microfusion cells",
		"Mr. House",
		"mutants",
		"NCR",
		"New Vegas",
		"Nuka-Cola",
		"outsider",
		"parcel",
		"Pipboy-3000",
		"platinum chip",
		"Powder Gangers",
		"power armor",
		"prospector",
		"radroach",
		"raider",
		"riot shotgun",
		"RobCo Industries",
		"robot",
		"scavenger",
		"Scourge of Humanity",
		"securitrons",
		"Shishkebab",
		"sledgehammer",
		"Sleeptron 3000",
		"stealth boy",
		"stimpaks",
		"super mutants",
		"super sledge",
		"Survivalist's rifle",
		"terminal",
		"tesla armor",
		"The Burned Man",
		"The Courier",
		"Three Dog",
		"Tunnel Snakes",
		"vaccuum tube",
		"VATS",
		"Vault 101",
		"vault dweller",
		"virtual reality",
		"wanderer",
		"wasteland",
		"wastelander",
		"White Glove Society",
		"yao guai",
		"yes man",
		"Yes, I Play With Dolls",
		"necrotic post-human",
		"glowing one",
		"ghoulification",
		"mole rats",
		"bloatfly",
		"centaur",
		"dog",
		"fireant",
		"mirelurk",
		"radscorpion",
		"dwarf",
		"gecko",
		"iguana",
		"mutated rat pig",
		"bighorner",
		"nightkin",
	);
	return $array;
}

function list_batman() {
	$array=array(
		"Joker",
		"Where does he get those wonderful toys",
		"Bruce Wayne",
		"Gotham City",
		"Arkham Asylum",
	);
	return $array;
}

function list_technobabble() {
	$array=array_merge($array,list_startrek_technobabble(), list_starwars_technobabble(), list_doctorwho_technobabble() );
	return $array;
}

function list_starwars_technobabble() {
	$array=array(
		"power converter",
		"carbon scoring",
		"coolant",
		"deflector grille",
		"subsonic field emitter",
		"thermal exhaust port",
		"navcomputer",
		"Midochlorians",
		"phototropic shielding",
	);
	return $array;
}

function list_starwars() {
	$array=array(
		"tautans",
		"Mos Eisley",
		"lightsaber",
		"stormtrooper",
	);
	$array=array_merge($array, list_starwars_technobabble() );
	return $array;
}

function list_pokemon() {
	$array=get_csv_path();
	return $array;
}

function list_doctorwho() {
	$array=array(
		"TARDIS",
		"Amy Pond",
		"sexy",
		"Pandorica",
		"Dalek",
		"Cyberman",
		"The Silence",
		"Weeping Angels",
	);
	$array=array_merge($array, list_doctorwho_technobabble() );
	return $array;
}

function list_doctorwho_technobabble() {
	$array=array(
		"telepathic-barrier",
		"psychic paper",
		"cloaking field",
		"computer sphere",
		"crucible energy core",
		"dimension vault",
		"polycarbide",
		"progenitor",
		"videoscope",
		"visualiser",
		"voltoscope",
		"temporal shift",
		"temporal stabiliser",
		"time controller",
		"time corridor",
		"schizoid accelerator",
		"seismic detector",
		"gravity beam",
		"gravity bubble",
		"gunstick",
		"bio-electric dampening field",
		"dalekanium",
		"psycho-kinetic threshold manipulator",
	);
	return $array;
}

function list_startrek() {
	$array=array(
		"admiral",
		"Andoreans",
		"Argus X",
		"assimiliate",
		"astrometrics",
		"atmosphere",
		"away team",
		"Bajoran",
		"beam me up",
		"Betazoid",
		"boarding party",
		"boldly go",
		"borg cube",
		"borg drones",
		"borg",
		"bridge",
		"cargo hold",
		"Data",
		"deep-space",
		"Delta quadrant",
		"diplomatic",
		"Earth",
		"emergency medical hologram",
		"engineering",
		"Enterprise",
		"fencing",
		"galaxy",
		"Gene Roddenberry",
		"Genesis device",
		"holodeck",
		"hydrophonics",
		"James T. Kirk",
		"Khan",
		"Klingon",
		"Kobayashi Maru",
		"LCARS",
		"main engineering",
		"Milky Way",
		"mind-meld",
		"Mr. Spock",
		"NCC-1701-E",
		"nebula",
		"Cardassians",
		"Ferengi",
		"dabo girl",
		"first officer",
		"number one",
		"Neutral Zone",
		"peace",
		"phaser banks",
		"photon torpedo",
		"piller-filler",
		"Prime Directive",
		"Q",
		"rear admiral",
		"refit",
		"Romulan",
		"San Francisco",
		"saucer section",
		"scanning",
		"science officer",
		"Scotty",
		"shields",
		"shuttlebay",
		"sickbay",
		"spacedock",
		"Species 8472",
		"sporocystian lifeform",
		"Stardate",
		"Starfleet",
		"starship",
		"stellar cartography",
		"subspace",
		"Sulu",
		"Temporal Prime Directive",
		"temporal vortex",
		"timeship",
		"transporters",
		"Tribbles",
		"turbolift",
		"Vulcan neck pinch",
		"warp core",
		"warp drive",
		"Wolf 359",
		"wormhole",
		"Tiberius",
	);
	
	$array=array_merge($array,list_startrek_technobabble());
	return $array;
}

function list_startrek_technobabble() {
	$array=array(
		"airlock",
		"android",
		"antiproton",
		"antiproton weapon",
		"black star",
		"cloaking device",
		"cochranes",
		"corbomite",
		"data sphere",
		"deflector dish",
		"depolarised",
		"deuterium",
		"dilithium crystal",
		"energy field",
		"graviton burst",
		"gravity well",
		"impulse engines",
		"interplexing beacon",
		"inverse phasing",
		"inverse tachyon beam",
		"level 3 diagnostic",
		"magnetic deflection",
		"matter-antimatter implosion",
		"medical scanner",
		"medical tricorder",
		"sensor beam",
		"antimatter injector",
		"mobile emitter",
		"modulation",
		"nebula",
		"nanoprobes",
		"neutrino emissions",
		"non-corporeal",
		"phaser banks",
		"photon torpedo",
		"piller-filler",
		"plasma coolant",
		"plasma drift",
		"plasma torpedo",
		"positronic network",
		"power drain",
		"probes",
		"proton bursts",
		"quantum phase",
		"quantum slipstream drive",
		"quantum torpedos",
		"replicator",
		"ryetalyn",
		"shields",
		"spatial scission",
		"sporocystian lifeform",
		"stellar cartography",
		"subspace",
		"tachyon beam",
		"tachyon particles",
		"temporal paradox",
		"temporal vortex",
		"timeship",
		"transporters",
		"transwarp coil",
		"transwarp conduits",
		"Theta radiation",
		"turbolift",
		"warp core",
		"warp core breech",
		"warp drive",
		"warp engine",
		"warp nacelle",
		"wormhole",
	);
	return $array;
}