<?php 

function list_ipsums(){
	
	$array=array(
		"Video Games",
		// "RPGs",
		// "Star Wars",
		"Fallout",
		// "Star Trek",
		// "Batman"
	);
	return $array;
}

function list_videogames() {
	$array=array(
		"1-UP",
		"8-bit",
		"A Boy and his Blob",
		"achievement unlocked",
		"adventure game",
		"arcade game",
		"auto-fire",
		"boss",
		"Burger Time",
		"cheat code",
		"co-op",
		"console",
		"controller",
		"cowabunga",
		"crafting",
		"death match",
		"directional pad",
		"Donkey Kong",
		"Dr. Wily",
		"edutainment",
		"EGM",
		"finish him",
		"fire flower",
		"first-person shooter",		
		"freakin' camper",
		"Galaga",
		"GameBoy",
		"GamePro",
		"god mode",
		"goddamn casuals",
		"Goomba",
		"Grand Theft Auto",
		"griefer",
		"grinding",
		"Guybrush Threepwood",
		"hack and slash",
		"hadoken",
		"healer",
		"high score",
		"hit points",
		"indie",
		"Inky",
		"Koopa Troopa",
		"last boss",
		"lightgun",
		"Mame",
		"Maniac Mansion",
		"Mario",
		"Masamune",
		"mini-boss",
		"multiplayer",
		"Murasame",
		"mushrooms",
		"n00b",
		"Nintendo",
		"NPC",
		"open world",
		"pacu pacu",
		"power-up",
		"Princess Toadstool",
		"questing",
		"rag-doll physics",
		"real-time strategy",
		"role-playing game",
		"Samus",
		"save point",
		"score",
		"Sega",
		"Sheng Long",
		"Shigeru Miyamoto",
		"shoryuken",
		"side-scrolling",
		"single-player",
		"Solid Snake",
		"spawn point",
		"special attack",
		"sprites",
		"strafing",
		"strategy guide",
		"survival horror",
		"tanuki suit",
		"Tri-force",
		"warp pipes",
		"Wiimote",
	);
	return $array;
}

function list_fallout() {
	$array=array(
		"Ain't That a Kick in the Head",
		"assault carbine",
		"Benny",
		"Boomers",
		"brahman milk",
		"brahman",
		"Brotherhood of Steel",
		"caravan",
		"cazadores",
		"chainsaw",
		"chems",
		"cowboy repeater",
		"deathclaws",
		"Doesn't Play Well with Others",
		"Elder",
		"feral ghoul",
		"Galaxy News Radio",
		"ghost",
		"Great Khans",
		"Hail Caesar",
		"Harold",
		"hunting rifle",
		"Hydra",
		"Jet",
		"karma",
		"lead pipe",
		"Little Lamplight",
		"Lone Wanderer",
		"Love the Bomb",
		"Maria",
		"Megaton",
		"Mr. House",
		"mutants",
		"NCR",
		"New Vegas",
		"Nuka-Cola",
		"outsider",
		"Pipboy 3000",
		"Powder Gangers",
		"power-armor",
		"prospector",
		"radroach",
		"raider",
		"riot shotgun",
		"RobCo Industries",
		"scavenger",
		"Scourge of Humanity",
		"Shishkebab",
		"sledgehammer",
		"stimpaks",
		"super mutants",
		"super sledge",
		"Survivalist's rifle",
		"The Burned Man",
		"The Courier",
		"Three Dog",
		"Tunnel Snakes",
		"VATS",
		"Vault 101",
		"vault dweller",
		"wanderer",
		"wasteland",
		"wastelander",
		"White Glove Society",
		"yao guai",
		"Yes, I Play With Dolls",
	);
	return $array;
}

function list_batman() {
	$array=array(
		"Joker",
		"Where does he get those wonderful toys",
		"Bruce Wayne",
		"Gotham City",
		"Arkham Asylum",
	);
	return $array;
}

function list_starwars() {
	$array=array(
		"tautans",
		"Mos Eisley",
		"lightsaber",
		"stormtrooper",
	);
	return $array;
}

function list_startrek() {
	$array=array(
		"Andoreans",
		"beam me up",
		"borg",
		"Enterprise",
		"Galaxy class",
		"holodeck",
		"James T. Kirk",
		"medical scanner",
		"mind-meld",
		"Mr. Spock",
		"photon torpedos",
		"Prime Directive",
		"scanning",
		"Starfleet",
		"Sulu",
		"transporters",
		"Tribbles",
		"Vulcan neck pinch",
		"warp 1",
		"warp drive",
		
	);
	return $array;
}